-- MySQL Script generated by MySQL Workbench
-- Sat Sep  2 15:20:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto_adso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto_adso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_adso` DEFAULT CHARACTER SET utf8 ;
USE `proyecto_adso` ;

-- -----------------------------------------------------
-- Table `proyecto_adso`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`cargo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `NIT` INT NULL,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`tipo_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`tipo_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`compras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` VARCHAR(450) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `proveedor_id` INT NOT NULL,
  `tipo_producto_id` INT NOT NULL,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `proveedor_id`, `tipo_producto_id`),
  INDEX `fk_compras_proveedor1_idx` (`proveedor_id` ASC),
  INDEX `fk_compras_tipo_producto1_idx` (`tipo_producto_id` ASC),
  CONSTRAINT `fk_compras_proveedor1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `proyecto_adso`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_tipo_producto1`
    FOREIGN KEY (`tipo_producto_id`)
    REFERENCES `proyecto_adso`.`tipo_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `establecimiento` VARCHAR(45) NULL DEFAULT NULL,
  `empleado_id` INT NULL DEFAULT NULL,
  `total` INT NULL DEFAULT NULL,
  `factura` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`detalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `factura` INT NULL DEFAULT NULL,
  `producto` INT NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `precio` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `factura_id` INT NOT NULL,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `factura_id`),
  INDEX `fk_detalles_factura1_idx` (`factura_id` ASC),
  CONSTRAINT `fk_detalles_factura1`
    FOREIGN KEY (`factura_id`)
    REFERENCES `proyecto_adso`.`factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`estado_empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`estado_empleados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`empleados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `celular` VARCHAR(45) NULL DEFAULT NULL,
  `genero` VARCHAR(45) NULL DEFAULT NULL,
  `contraseña` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `cargo_id` INT NOT NULL,
  `estado_empleados_id` INT NOT NULL,
  `update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `cargo_id`, `estado_empleados_id`),
  INDEX `fk_empleados_cargo1_idx` (`cargo_id` ASC),
  INDEX `fk_empleados_estado_empleados1_idx` (`estado_empleados_id` ASC),
  CONSTRAINT `fk_empleados_cargo1`
    FOREIGN KEY (`cargo_id`)
    REFERENCES `proyecto_adso`.`cargo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleados_estado_empleados1`
    FOREIGN KEY (`estado_empleados_id`)
    REFERENCES `proyecto_adso`.`estado_empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`estado usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`estado usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`estado_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`estado_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`logs` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `uptude_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`pgr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`pgr` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `peticion` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `quejas` VARCHAR(45) NULL,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`log_pqr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`log_pqr` (
  `logs_id` INT NOT NULL,
  `pgr_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`logs_id`, `pgr_id`),
  INDEX `fk_log_pqr_pgr1_idx` (`pgr_id` ASC) ,
  CONSTRAINT `fk_log_pqr_logs1`
    FOREIGN KEY (`logs_id`)
    REFERENCES `proyecto_adso`.`logs` (`id`),
  CONSTRAINT `fk_log_pqr_pgr1`
    FOREIGN KEY (`pgr_id`)
    REFERENCES `proyecto_adso`.`pgr` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `celular` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `contrasena` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `estado usuarios_id` INT NULL,
  `updete_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `estado usuarios_id`),
  INDEX `fk_usuarios_estado usuarios1_idx` (`estado usuarios_id` ASC) ,
  CONSTRAINT `fk_usuarios_estado usuarios1`
    FOREIGN KEY (`estado usuarios_id`)
    REFERENCES `proyecto_adso`.`estado usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`log_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`log_usuarios` (
  `id` INT NOT NULL,
  `logs_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`id`, `logs_id`, `usuarios_id`),
  INDEX `fk_log_usuarios_logs1_idx` (`logs_id` ASC) ,
  INDEX `fk_log_usuarios_usuarios1_idx` (`usuarios_id` ASC) ,
  CONSTRAINT `fk_log_usuarios_logs1`
    FOREIGN KEY (`logs_id`)
    REFERENCES `proyecto_adso`.`logs` (`id`),
  CONSTRAINT `fk_log_usuarios_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `proyecto_adso`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`logs_empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`logs_empleados` (
  `idlogs_empleados` INT NOT NULL,
  `logs_id` INT NOT NULL,
  `empleados_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `uodate_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idlogs_empleados`, `logs_id`, `empleados_id`),
  INDEX `fk_logs_empleados_logs1_idx` (`logs_id` ASC) ,
  INDEX `fk_logs_empleados_empleados1_idx` (`empleados_id` ASC) ,
  CONSTRAINT `fk_logs_empleados_empleados1`
    FOREIGN KEY (`empleados_id`)
    REFERENCES `proyecto_adso`.`empleados` (`id`),
  CONSTRAINT `fk_logs_empleados_logs1`
    FOREIGN KEY (`logs_id`)
    REFERENCES `proyecto_adso`.`logs` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`medio_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`medio_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `medio_pago` VARCHAR(45) NULL DEFAULT NULL,
  `usuarios_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `usuarios_id`),
  INDEX `fk_medio_pago_usuarios1_idx` (`usuarios_id` ASC) ,
  CONSTRAINT `fk_medio_pago_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `proyecto_adso`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad` VARCHAR(45) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `medio_pago_id` INT NOT NULL,
  `factura_id` INT NOT NULL,
  PRIMARY KEY (`id`, `medio_pago_id`, `factura_id`),
  INDEX `fk_ventas_medio_pago1_idx` (`medio_pago_id` ASC) ,
  INDEX `fk_ventas_factura1_idx` (`factura_id` ASC) ,
  CONSTRAINT `fk_ventas_medio_pago1`
    FOREIGN KEY (`medio_pago_id`)
    REFERENCES `proyecto_adso`.`medio_pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_factura1`
    FOREIGN KEY (`factura_id`)
    REFERENCES `proyecto_adso`.`factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `catidad` VARCHAR(450) NULL DEFAULT NULL,
  `tipo_producto_id` INT NULL DEFAULT NULL,
  `precio` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `ventas_id` INT NOT NULL,
  `ventas_medio_pago_id` INT NOT NULL,
  `ventas_factura_id` INT NOT NULL,
  `proveedor_id` INT NOT NULL,
  `estado_producto_id` INT NOT NULL,
  `tipo_producto_id1` INT NOT NULL,
  `ventas_id1` INT NOT NULL,
  `ventas_medio_pago_id1` INT NOT NULL,
  `ventas_factura_id1` INT NOT NULL,
  `udate_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `ventas_id`, `ventas_medio_pago_id`, `ventas_factura_id`, `proveedor_id`, `estado_producto_id`, `tipo_producto_id1`, `ventas_id1`, `ventas_medio_pago_id1`, `ventas_factura_id1`),
  INDEX `fk_productos_proveedor1_idx` (`proveedor_id` ASC) ,
  INDEX `fk_productos_estado_producto1_idx` (`estado_producto_id` ASC) ,
  INDEX `fk_productos_tipo_producto1_idx` (`tipo_producto_id1` ASC) ,
  INDEX `fk_productos_ventas1_idx` (`ventas_id1` ASC, `ventas_medio_pago_id1` ASC, `ventas_factura_id1` ASC) ,
  CONSTRAINT `fk_productos_proveedor1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `proyecto_adso`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_estado_producto1`
    FOREIGN KEY (`estado_producto_id`)
    REFERENCES `proyecto_adso`.`estado_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_tipo_producto1`
    FOREIGN KEY (`tipo_producto_id1`)
    REFERENCES `proyecto_adso`.`tipo_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_ventas1`
    FOREIGN KEY (`ventas_id1` , `ventas_medio_pago_id1` , `ventas_factura_id1`)
    REFERENCES `proyecto_adso`.`ventas` (`id` , `medio_pago_id` , `factura_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`logs_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`logs_productos` (
  `id` INT NOT NULL,
  `logs_id` INT NOT NULL,
  `productos_id` INT NOT NULL,
  `productos_ventas_id` INT NOT NULL,
  `productos_ventas_medio_pago_id` INT NOT NULL,
  `productos_ventas_factura_id` INT NOT NULL,
  `productos_proveedor_id` INT NOT NULL,
  `productos_estado_producto_id` INT NOT NULL,
  `productos_tipo_producto_id1` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `logs_id`, `productos_id`, `productos_ventas_id`, `productos_ventas_medio_pago_id`, `productos_ventas_factura_id`, `productos_proveedor_id`, `productos_estado_producto_id`, `productos_tipo_producto_id1`),
  INDEX `fk_logs_productos_logs1_idx` (`logs_id` ASC) ,
  INDEX `fk_logs_productos_productos1_idx` (`productos_id` ASC, `productos_ventas_id` ASC, `productos_ventas_medio_pago_id` ASC, `productos_ventas_factura_id` ASC, `productos_proveedor_id` ASC, `productos_estado_producto_id` ASC, `productos_tipo_producto_id1` ASC) ,
  CONSTRAINT `fk_logs_productos_logs1`
    FOREIGN KEY (`logs_id`)
    REFERENCES `proyecto_adso`.`logs` (`id`),
  CONSTRAINT `fk_logs_productos_productos1`
    FOREIGN KEY (`productos_id` , `productos_ventas_id` , `productos_ventas_medio_pago_id` , `productos_ventas_factura_id` , `productos_proveedor_id` , `productos_estado_producto_id` , `productos_tipo_producto_id1`)
    REFERENCES `proyecto_adso`.`productos` (`id` , `ventas_id` , `ventas_medio_pago_id` , `ventas_factura_id` , `proveedor_id` , `estado_producto_id` , `tipo_producto_id1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`estado_domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`estado_domicilio` (
  `idestado_domicilio` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idestado_domicilio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`domicilios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`domicilios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ventas_id` INT NOT NULL,
  `ventas_medio_pago_id` INT NOT NULL,
  `ventas_factura_id` INT NOT NULL,
  `estado_domicilio_idestado_domicilio` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `empleados_id` INT NOT NULL,
  `empleados_cargo_id` INT NOT NULL,
  `empleados_estado_empleados_id` INT NOT NULL,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `ventas_id`, `ventas_medio_pago_id`, `ventas_factura_id`, `estado_domicilio_idestado_domicilio`, `empleados_id`, `empleados_cargo_id`, `empleados_estado_empleados_id`),
  INDEX `fk_domicilios_ventas1_idx` (`ventas_id` ASC, `ventas_medio_pago_id` ASC, `ventas_factura_id` ASC) ,
  INDEX `fk_domicilios_estado_domicilio1_idx` (`estado_domicilio_idestado_domicilio` ASC) ,
  INDEX `fk_domicilios_empleados1_idx` (`empleados_id` ASC, `empleados_cargo_id` ASC, `empleados_estado_empleados_id` ASC) ,
  CONSTRAINT `fk_domicilios_ventas1`
    FOREIGN KEY (`ventas_id` , `ventas_medio_pago_id` , `ventas_factura_id`)
    REFERENCES `proyecto_adso`.`ventas` (`id` , `medio_pago_id` , `factura_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domicilios_estado_domicilio1`
    FOREIGN KEY (`estado_domicilio_idestado_domicilio`)
    REFERENCES `proyecto_adso`.`estado_domicilio` (`idestado_domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domicilios_empleados1`
    FOREIGN KEY (`empleados_id` , `empleados_cargo_id` , `empleados_estado_empleados_id`)
    REFERENCES `proyecto_adso`.`empleados` (`id` , `cargo_id` , `estado_empleados_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`comantarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`comantarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(255) NULL,
  `usuarios_id` INT NOT NULL,
  `usuarios_estado usuarios_id` INT NOT NULL,
  `productos_id` INT NOT NULL,
  `productos_ventas_id` INT NOT NULL,
  `productos_ventas_medio_pago_id` INT NOT NULL,
  `productos_ventas_factura_id` INT NOT NULL,
  `productos_proveedor_id` INT NOT NULL,
  `productos_estado_producto_id` INT NOT NULL,
  `productos_tipo_producto_id1` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `usuarios_id`, `usuarios_estado usuarios_id`, `productos_id`, `productos_ventas_id`, `productos_ventas_medio_pago_id`, `productos_ventas_factura_id`, `productos_proveedor_id`, `productos_estado_producto_id`, `productos_tipo_producto_id1`),
  INDEX `fk_comantarios_usuarios1_idx` (`usuarios_id` ASC, `usuarios_estado usuarios_id` ASC) ,
  INDEX `fk_comantarios_productos1_idx` (`productos_id` ASC, `productos_ventas_id` ASC, `productos_ventas_medio_pago_id` ASC, `productos_ventas_factura_id` ASC, `productos_proveedor_id` ASC, `productos_estado_producto_id` ASC, `productos_tipo_producto_id1` ASC) ,
  CONSTRAINT `fk_comantarios_usuarios1`
    FOREIGN KEY (`usuarios_id` , `usuarios_estado usuarios_id`)
    REFERENCES `proyecto_adso`.`usuarios` (`id` , `estado usuarios_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comantarios_productos1`
    FOREIGN KEY (`productos_id` , `productos_ventas_id` , `productos_ventas_medio_pago_id` , `productos_ventas_factura_id` , `productos_proveedor_id` , `productos_estado_producto_id` , `productos_tipo_producto_id1`)
    REFERENCES `proyecto_adso`.`productos` (`id` , `ventas_id` , `ventas_medio_pago_id` , `ventas_factura_id` , `proveedor_id` , `estado_producto_id` , `tipo_producto_id1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_adso`.`novedades_domicilios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_adso`.`novedades_domicilios` (
  `id` INT NOT NULL,
  `domicilios_id` INT NOT NULL,
  `domicilios_ventas_id` INT NOT NULL,
  `domicilios_ventas_medio_pago_id` INT NOT NULL,
  `domicilios_ventas_factura_id` INT NOT NULL,
  `domicilios_estado_domicilio_idestado_domicilio` INT NOT NULL,
  `domicilios_empleados_id` INT NOT NULL,
  `domicilios_empleados_cargo_id` INT NOT NULL,
  `domicilios_empleados_estado_empleados_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `domicilios_id`, `domicilios_ventas_id`, `domicilios_ventas_medio_pago_id`, `domicilios_ventas_factura_id`, `domicilios_estado_domicilio_idestado_domicilio`, `domicilios_empleados_id`, `domicilios_empleados_cargo_id`, `domicilios_empleados_estado_empleados_id`),
  INDEX `fk_novedades_domicilios_domicilios1_idx` (`domicilios_id` ASC, `domicilios_ventas_id` ASC, `domicilios_ventas_medio_pago_id` ASC, `domicilios_ventas_factura_id` ASC, `domicilios_estado_domicilio_idestado_domicilio` ASC, `domicilios_empleados_id` ASC, `domicilios_empleados_cargo_id` ASC, `domicilios_empleados_estado_empleados_id` ASC),
  CONSTRAINT `fk_novedades_domicilios_domicilios1`
    FOREIGN KEY (`domicilios_id` , `domicilios_ventas_id` , `domicilios_ventas_medio_pago_id` , `domicilios_ventas_factura_id` , `domicilios_estado_domicilio_idestado_domicilio` , `domicilios_empleados_id` , `domicilios_empleados_cargo_id` , `domicilios_empleados_estado_empleados_id`)
    REFERENCES `proyecto_adso`.`domicilios` (`id` , `ventas_id` , `ventas_medio_pago_id` , `ventas_factura_id` , `estado_domicilio_idestado_domicilio` , `empleados_id` , `empleados_cargo_id` , `empleados_estado_empleados_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
